image: circleci/node:9.11.1-browsers

stages:
  - build
  - staging
  # - production

build:
  stage: build
  script:
    - npm install --progress=false --non-interactive
    - npm build
  artifacts:
    paths:
      - build/
  only:
    - master

staging:
  type: deploy
  stage: staging
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY

  only:
    - master
# production:
#   type: deploy
#   stage: production
#   image: ruby:latest
#   script:
#     - apt-get update -qy
#     - apt-get install -y ruby-dev
#     - gem install dpl
#     - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY

#   only:
#     - master